name: cicd project
on: [push]

jobs:
  build-and-tests:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install --upgrade platformio

    - name: Run Unit Tests
      run: platformio test --environment native -f unit -v

    - name: Run Integration Tests
      run: platformio remote test --environment uno --ignore unit
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.platformioAgent }}

  deploy-firmware:
    name: Deploy firmware
    needs: build-and-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install --upgrade platformio

    - name: Deploy firmware
      run: platformio remote run --environment uno --target upload
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.platformioAgent }}